### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xcypher78** [phlmox/BurpJSLinkFinderv2#3]
Error in URL decode.

latest version of burp java and jython

**Comment by phlmox** [comment]
Hi, could you please share the error? And which one do you use, the normal version or the community edition?

**Comment by xcypher78** [comment]
pro version

**Comment by phlmox** [comment]
Would you mind sharing the error message when you are available?

**Comment by xcypher78** [comment]
the error message is "Error in URL decode." in output

**Comment by phlmox** [comment]
I understand, but I need to see the URL to determine what’s causing this issue. Can you share the URL?

**Comment by xcypher78** [comment]
impossible to know because your extension grab all  .js urls correct ?

but here it appears like this 

[-] URL excluded [THE URL]
Error in URL decode.
Error in URL decode.
Error in URL decode.
...

**Comment by xcypher78** [comment]
NotImplementedError: 'BurpExtender' object does not implement abstract method 'doActiveScan' from 'burp.IScannerCheck'

	at org.python.core.Py.NotImplementedError(Py.java:138)
	at org.python.compiler.ProxyCodeHelpers.notImplementedAbstractMethod(ProxyCodeHelpers.java:97)
	at org.python.proxies.__main__$BurpExtender$1.doActiveScan(Unknown Source)
	at burp.Zvca.activeAudit(Unknown Source)
	at burp.Zuj2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by phlmox** [comment]
Fixed the issue by adding doActiveScan function
